[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

# Use root .env file instead of contracts/.env
env_file = "../.env"

# Allow file operations for deployment scripts
fs_permissions = [{ access = "read-write", path = "./" }, { access = "read-write", path = "../" }]

# Remappings for OpenZeppelin contracts
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
